### ISSUE TITLE
Unsupported prop_type value

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-billsdotcom#27]
Bills.com is submitting leads with `prop_type=Single+Family+Residence`. This is not supported by the [parsePropertyType()](https://github.com/activeprospect/leadconduit-integration-billsdotcom/blob/115beb251cd814cb33a7cd7945f42b06e67e2abe/src/inbound.coffee#L235-L243) function.

The net effect is that the "Mortgage Property Type" field is not being populated.

**Comment by alexkwolfe** [comment]
Same problem with `prop_intend_use=Primary+Residence`. It is not supported by the [parsePropertyUse()](https://github.com/activeprospect/leadconduit-integration-billsdotcom/blob/115beb251cd814cb33a7cd7945f42b06e67e2abe/src/inbound.coffee#L226-L232) function

**Comment by alexkwolfe** [comment]
Here's another `prop_type=Condominium%2FTownhome`. I suspect that Bills.com gave us bad information on the values they'd be submitting for these fields. Maybe some soft of fuzzy matching would be better than looking for exact strings.

**Comment by zalary** [comment]
LCN fields considers Townhome and Condo to be different things, but Bills.com considers it to be one.  Is there a preference for which we assign?

cc @alexkwolfe @kcaponeAP

**Comment by alexkwolfe** [comment]
I don't have a preference.
