### ISSUE TITLE
Please add add a field for Velocify campaignID

### ISSUE THREAD

**Issue by activeprospect-support** [activeprospect/leadconduit-integration-billsdotcom#29]
We need to allow Bills.com to dynamically change their campaign ID based on constantly changing criteria.

currently vel_camp_id is what they are sending, I suggest we rename this to something fitting the LCN standard. 

Thoughts? We need this piece in order to go live with Bridgeview / Bills.com

**Comment by kcaponeAP** [comment]
I can see how this is something that all integrations would benefit from as well.
