### ISSUE TITLE
Quotations do not seem correct

### ISSUE THREAD

**Issue by ros3bud** [activeprospect/leadconduit-integration-billsdotcom#30]
When I cloned this down and went to make a change, I noticed that something was off with the way the quotes are in the inbound.coffee file. @zalary - can we please discuss this at your earliest convenience as it's not clear to me what the intention is.

**Comment by zalary** [comment]
what sort of thing is 'off'?

**Comment by ros3bud** [comment]
Please disregard!

**Comment by zalary** [comment]
The quotes look ok to me and afaik this is functioning in production, so please let me know what you find out.

**Comment by ros3bud** [comment]
When I do a fresh clone it looks like a quote is missing, might be my editor. All tests are passing.  I can show you when we're both in the office.
