### ISSUE TITLE
Please add leadid_id to the Bills.com integration

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-billsdotcom#33]
Referencing: https://github.com/activeprospect/leadconduit-integration-lowermybills/issues/30

Can we please add leadid_id to this integration. It should route to our internal field 'leadid_id'

@alexj please prioritize!

**Comment by alexj** [comment]
Lynda, can you take a look at this please? Hopefully it's pretty straightforward to knock out quickly.

**Comment by ros3bud** [comment]
Yes, on it.

**Comment by ros3bud** [comment]
Fixed in version 0.2.4

**Comment by kcaponeAP** [comment]
Has this been deployed to production?

**Comment by cgrayson** [comment]
It has now. (Along with #35.)
