### ISSUE TITLE
Add campaign_id to bills.com inbound

### ISSUE THREAD

**Issue by alexj** [activeprospect/leadconduit-integration-billsdotcom#37]
Once it has been added as a standard field (https://github.com/activeprospect/leadconduit-fields/issues/89), please add `campaign_id` to the integration. Please notify Hansen and me when it has rolled into production.

**Comment by jgrayson676** [comment]
Which bills.com field should be mapped to `campaign_id`?

**Comment by alexj** [comment]
The customer will map the inbound `vel_camp_id` field, but I have a feeling that is specific for Velocify, so not something we want automatically mapped. Sorry, I missed the `vel_` part of that in the initial request. Let's hold off on this issue for now, and just role out the `campaign_id` field.

**Comment by cgrayson** [comment]
Duplicate, more or less, of #38.
